#!/usr/bin/env php
<?php

namespace PushTester;

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use PushTester\Command\SendPushCommand;

$appVersion = '1.0.0';

$application = new Application('Push tester', $appVersion);

$application->add(new SendPushCommand());

$application->run();
