#!/usr/bin/env php
<?php

namespace PushTester;

require __DIR__.'/vendor/autoload.php';

use PushTester\Command\SelfUpdateCommand;
use PushTester\Command\SendPushCommand;
use Symfony\Component\Console\Application;

$appVersion = '1.0.0';

$application = new Application('Push tester', $appVersion);

$application->add(new SendPushCommand());
$application->add(new SelfUpdateCommand());

$application->run();
